#!/bin/bash
# -----------------------------------------------------------------------------
# docker-starbound /start script
#
# Authors: Isaac Bythewood
# Updated: Jan 26th, 2014
# -----------------------------------------------------------------------------


# Run the starbound server
/opt/starbound/linux64/starbound_server

