#!/bin/bash
# -----------------------------------------------------------------------------
# docker-starbound /start script
#
# Authors: Isaac Bythewood
# Updated: Jan 30th, 2014
# -----------------------------------------------------------------------------


# Run the starbound server
/opt/starbound/linux32/starbound_server

